/* automatically generated from panel-preferences-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (panel_preferences_dialog_ui)
#endif
#ifdef __GNUC__
static const char panel_preferences_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char panel_preferences_dialog_ui[] =
#endif
{
  /* modified by youtian 2016.04.10 */
  "<?xml version=\"1.0\"?><interface><requires lib=\"gtk+\" version=\"2.24"
  "\"/><object class=\"GtkListStore\" id=\"mode-store\"><columns><column t"
  "ype=\"gchararray\"/></columns><data><row><col id=\"0\" translatable=\"y"
  "es\">Horizontal</col></row><row><col id=\"0\" translatable=\"yes\">Vert"
  "ical</col></row><row><col id=\"0\" translatable=\"yes\">Deskbar</col></"
  "row></data></object><object class=\"GtkListStore\" id=\"panel-store\"><"
  "columns><column type=\"gint\"/><column type=\"gchararray\"/></columns><"
  "/object><object class=\"GtkListStore\" id=\"output-store\"><columns><co"
  "lumn type=\"gchararray\"/><column type=\"gchararray\"/></columns></obje"
  "ct><object class=\"GtkListStore\" id=\"autohide-behavior-store\"><colum"
  "ns><column type=\"gchararray\"/></columns><data><row><col id=\"0\" tran"
  "slatable=\"yes\">Never</col></row><row><col id=\"0\" translatable=\"yes"
  "\">Intelligently</col></row><row><col id=\"0\" translatable=\"yes\">Alw"
  "ays</col></row></data></object><object class=\"GtkListStore\" id=\"styl"
  "es-store\"><columns><column type=\"gchararray\"/></columns><data><row><"
  "col id=\"0\" translatable=\"yes\">None (use system style)</col></row><r"
  "ow><col id=\"0\" translatable=\"yes\">Solid color</col></row><row><col "
  "id=\"0\" translatable=\"yes\">Background image</col></row></data></obje"
  "ct><object class=\"GtkAdjustment\" id=\"size\"><property name=\"value\""
  ">16</property><property name=\"lower\">16</property><property name=\"up"
  "per\">128</property><property name=\"step_increment\">1</property><prop"
  "erty name=\"page_increment\">10</property></object><object class=\"GtkA"
  "djustment\" id=\"length\"><property name=\"value\">25</property><proper"
  "ty name=\"lower\">1</property><property name=\"upper\">100</property><p"
  "roperty name=\"step_increment\">1</property><property name=\"page_incre"
  "ment\">10</property></object><object class=\"GtkAdjustment\" id=\"nrows"
  "\"><property name=\"value\">1</property><property name=\"lower\">1</pro"
  "perty><property name=\"upper\">6</property><property name=\"step_increm"
  "ent\">1</property><property name=\"page_increment\">1</property></objec"
  "t><object class=\"GtkAdjustment\" id=\"background-alpha\"><property nam"
  "e=\"value\">100</property><property name=\"upper\">100</property><prope"
  "rty name=\"step_increment\">1</property><property name=\"page_increment"
  "\">10</property></object><object class=\"GtkAdjustment\" id=\"enter-opa"
  "city\"><property name=\"value\">100</property><property name=\"upper\">"
  "100</property><property name=\"step_increment\">1</property><property n"
  "ame=\"page_increment\">10</property></object><object class=\"GtkAdjustm"
  "ent\" id=\"leave-opacity\"><property name=\"value\">100</property><prop"
  "erty name=\"upper\">100</property><property name=\"step_increment\">1</"
  "property><property name=\"page_increment\">10</property></object><objec"
  "t class=\"GtkSizeGroup\" id=\"display-sizegroup\"><widgets><widget name"
  "=\"label13\"/><widget name=\"label1\"/></widgets></object><object class"
  "=\"GtkSizeGroup\" id=\"bg-sizegroup\"><widgets><widget name=\"label7\"/"
  "><widget name=\"label15\"/><widget name=\"label16\"/><widget name=\"lab"
  "el19\"/></widgets></object><object class=\"XfceTitledDialog\" id=\"dial"
  "og\"><property name=\"title\" translatable=\"yes\">Panel</property><pro"
  "perty name=\"window_position\">center-on-parent</property><property nam"
  "e=\"icon_name\">xfce4-panel</property><property name=\"type_hint\">norm"
  "al</property><property name=\"has_separator\">False</property><child in"
  "ternal-child=\"vbox\"><object class=\"GtkVBox\" id=\"dialog-vbox1\"><pr"
  "operty name=\"visible\">True</property><property name=\"orientation\">v"
  "ertical</property><property name=\"spacing\">2</property><child><object"
  " class=\"GtkVBox\" id=\"plug-child\"><property name=\"visible\">True</p"
  "roperty><property name=\"border_width\">6</property><property name=\"or"
  "ientation\">vertical</property><property name=\"spacing\">12</property>"
  "<child><object class=\"GtkHBox\" id=\"hbox3\"><property name=\"visible\""
  ">True</property><property name=\"spacing\">6</property><child><object c"
  "lass=\"GtkComboBox\" id=\"panel-combobox\"><property name=\"visible\">T"
  "rue</property><property name=\"model\">panel-store</property><child><ob"
  "ject class=\"GtkCellRendererText\" id=\"cellrenderertext2\"/><attribute"
  "s><attribute name=\"text\">1</attribute></attributes></child></object><"
  "packing><property name=\"position\">0</property></packing></child><chil"
  "d><object class=\"GtkButton\" id=\"panel-add\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">True</property><property name=\"tooltip_text"
  "\" translatable=\"yes\">Add a new panel</property><child><object class="
  "\"GtkImage\" id=\"image1\"><property name=\"visible\">True</property><p"
  "roperty name=\"stock\">gtk-add</property></object></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"positio"
  "n\">1</property></packing></child><child><object class=\"GtkButton\" id"
  "=\"panel-remove\"><property name=\"visible\">True</property><property n"
  "ame=\"sensitive\">False</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">True</property><property nam"
  "e=\"tooltip_text\" translatable=\"yes\">Remove the currently selected p"
  "anel</property><child><object class=\"GtkImage\" id=\"image2\"><propert"
  "y name=\"visible\">True</property><property name=\"stock\">gtk-remove</"
  "property></object></child></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"position\">2</property></packing></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"position\">0</property></packing></child><child><object class=\""
  "GtkNotebook\" id=\"notebook\"><property name=\"visible\">True</property"
  "><property name=\"sensitive\">False</property><property name=\"can_focu"
  "s\">True</property><child><object class=\"GtkVBox\" id=\"vbox2\"><prope"
  "rty name=\"visible\">True</property><property name=\"border_width\">6</"
  "property><property name=\"orientation\">vertical</property><property na"
  "me=\"spacing\">6</property><child><object class=\"GtkFrame\" id=\"frame"
  "1\"><property name=\"visible\">True</property><property name=\"label_xa"
  "lign\">0</property><property name=\"shadow_type\">none</property><child"
  "><object class=\"GtkAlignment\" id=\"alignment1\"><property name=\"visi"
  "ble\">True</property><property name=\"left_padding\">12</property><chil"
  "d><object class=\"GtkVBox\" id=\"vbox3\"><property name=\"visible\">Tru"
  "e</property><property name=\"border_width\">6</property><property name="
  "\"orientation\">vertical</property><property name=\"spacing\">6</proper"
  "ty><child><object class=\"GtkHBox\" id=\"hbox1\"><property name=\"visib"
  "le\">True</property><property name=\"spacing\">12</property><child><obj"
  "ect class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</p"
  "roperty><property name=\"xalign\">0</property><property name=\"label\" "
  "translatable=\"yes\">M_ode:</property><property name=\"use_underline\">"
  "True</property><property name=\"mnemonic_widget\">mode</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkComb"
  "oBox\" id=\"mode\"><property name=\"visible\">True</property><property "
  "name=\"model\">mode-store</property><child><object class=\"GtkCellRende"
  "rerText\" id=\"cellrenderertext1\"/><attributes><attribute name=\"text\""
  ">0</attribute></attributes></child></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"position\">1</property></packi"
  "ng></child></object><packing><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkHBox\" id=\"output-box\"><pro"
  "perty name=\"visible\">True</property><property name=\"spacing\">12</pr"
  "operty><child><object class=\"GtkLabel\" id=\"label13\"><property name="
  "\"visible\">True</property><property name=\"xalign\">0</property><prope"
  "rty name=\"label\" translatable=\"yes\">O_utput:</property><property na"
  "me=\"use_underline\">True</property><property name=\"mnemonic_widget\">"
  "output-name</property></object><packing><property name=\"expand\">False"
  "</property><property name=\"position\">0</property></packing></child><c"
  "hild><object class=\"GtkComboBox\" id=\"output-name\"><property name=\""
  "visible\">True</property><property name=\"model\">output-store</propert"
  "y><child><object class=\"GtkCellRendererText\" id=\"cellrenderertext3\""
  "/><attributes><attribute name=\"text\">1</attribute></attributes></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"position\">1</property></packing></child></object><packing><pro"
  "perty name=\"position\">1</property></packing></child><child><object cl"
  "ass=\"GtkCheckButton\" id=\"span-monitors\"><property name=\"label\" tr"
  "anslatable=\"yes\">Span mo_nitors</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"receives_default\">False</property><property name=\"tooltip_text\""
  " translatable=\"yes\">Select this option to extend the panel over multi"
  "ple monitors.</property><property name=\"use_underline\">True</property"
  "><property name=\"draw_indicator\">True</property></object><packing><pr"
  "operty name=\"position\">2</property></packing></child><child><object c"
  "lass=\"GtkCheckButton\" id=\"position-locked\"><property name=\"label\""
  " translatable=\"yes\">_Lock panel</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"receives_default\">False</property><property name=\"tooltip_text\""
  " translatable=\"yes\">Select this option to hide the handles of the pan"
  "el and lock its position.</property><property name=\"use_underline\">Tr"
  "ue</property><property name=\"draw_indicator\">True</property></object>"
  "<packing><property name=\"position\">3</property></packing></child><chi"
  "ld><object class=\"GtkHBox\" id=\"hbox6\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"spacing\">12</property><child><object class=\"GtkLabel\" id=\"label"
  "20\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"xalign\">0</property><property na"
  "me=\"label\" translatable=\"yes\">Automatically hide the panel:</proper"
  "ty><property name=\"use_underline\">True</property><property name=\"mne"
  "monic_widget\">mode</property></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">0</property></packing></child><child><object class=\"Gtk"
  "ComboBox\" id=\"autohide-behavior\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"mo"
  "del\">autohide-behavior-store</property><child><object class=\"GtkCellR"
  "endererText\" id=\"cellrenderertext5\"/><attributes><attribute name=\"t"
  "ext\">0</attribute></attributes></child></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">1</property></packing></child></object><packin"
  "g><property name=\"expand\">True</property><property name=\"fill\">True"
  "</property><property name=\"position\">4</property></packing></child><c"
  "hild><object class=\"GtkCheckButton\" id=\"disable-struts\"><property n"
  "ame=\"label\" translatable=\"yes\">Don\'t _reserve space on borders</pr"
  "operty><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"receives_default\">False</proper"
  "ty><property name=\"tooltip_text\" translatable=\"yes\">Select this opt"
  "ion if you want maximized windows to cover the area behind the panel. T"
  "his only works when the panel is attached to a screen edge.</property><"
  "property name=\"use_underline\">True</property><property name=\"draw_in"
  "dicator\">True</property></object><packing><property name=\"position\">"
  "5</property></packing></child></object></child></object></child><child "
  "type=\"label\"><object class=\"GtkLabel\" id=\"label2\"><property name="
  "\"visible\">True</property><property name=\"label\" translatable=\"yes\""
  ">General</property><attributes><attribute name=\"weight\" value=\"bold\""
  "/></attributes></object></child></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"position\">0</property></packing>"
  "</child><child><object class=\"GtkFrame\" id=\"frame2\"><property name="
  "\"visible\">True</property><property name=\"label_xalign\">0</property>"
  "<property name=\"shadow_type\">none</property><child><object class=\"Gt"
  "kAlignment\" id=\"alignment2\"><property name=\"visible\">True</propert"
  "y><property name=\"left_padding\">12</property><child><object class=\"G"
  "tkTable\" id=\"table1\"><property name=\"visible\">True</property><prop"
  "erty name=\"border_width\">6</property><property name=\"n_rows\">4</pro"
  "perty><property name=\"n_columns\">2</property><property name=\"column_"
  "spacing\">12</property><property name=\"row_spacing\">6</property><chil"
  "d><object class=\"GtkLabel\" id=\"label3\"><property name=\"visible\">T"
  "rue</property><property name=\"xalign\">0</property><property name=\"la"
  "bel\" translatable=\"yes\">Row _Size (pixels):</property><property name"
  "=\"use_underline\">True</property><property name=\"mnemonic_widget\">si"
  "ze-scale</property></object><packing><property name=\"x_options\">GTK_F"
  "ILL</property></packing></child><child><object class=\"GtkLabel\" id=\""
  "label4\"><property name=\"visible\">True</property><property name=\"xal"
  "ign\">0</property><property name=\"label\" translatable=\"yes\">L_ength"
  " (%):</property><property name=\"use_underline\">True</property><proper"
  "ty name=\"mnemonic_widget\">length-scale</property></object><packing><p"
  "roperty name=\"top_attach\">2</property><property name=\"bottom_attach\""
  ">3</property><property name=\"x_options\">GTK_FILL</property></packing>"
  "</child><child><object class=\"GtkLabel\" id=\"label18\"><property name"
  "=\"visible\">True</property><property name=\"xalign\">0</property><prop"
  "erty name=\"label\" translatable=\"yes\">Num_ber of rows:</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"mnemonic_"
  "widget\">nrows-scale</property></object><packing><property name=\"top_a"
  "ttach\">1</property><property name=\"bottom_attach\">2</property><prope"
  "rty name=\"x_options\">GTK_FILL</property></packing></child><child><obj"
  "ect class=\"GtkHScale\" id=\"length-scale\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"update_policy\">discontinuous</property><property name=\"adjustmen"
  "t\">length</property><property name=\"digits\">0</property><property na"
  "me=\"value_pos\">right</property></object><packing><property name=\"lef"
  "t_attach\">1</property><property name=\"right_attach\">2</property><pro"
  "perty name=\"top_attach\">2</property><property name=\"bottom_attach\">"
  "3</property></packing></child><child><object class=\"GtkHScale\" id=\"s"
  "ize-scale\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"update_policy\">discontinuo"
  "us</property><property name=\"adjustment\">size</property><property nam"
  "e=\"digits\">0</property><property name=\"value_pos\">right</property><"
  "/object><packing><property name=\"left_attach\">1</property><property n"
  "ame=\"right_attach\">2</property></packing></child><child><object class"
  "=\"GtkHScale\" id=\"nrows-scale\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"updat"
  "e_policy\">discontinuous</property><property name=\"adjustment\">nrows<"
  "/property><property name=\"digits\">0</property><property name=\"value_"
  "pos\">right</property></object><packing><property name=\"left_attach\">"
  "1</property><property name=\"right_attach\">2</property><property name="
  "\"top_attach\">1</property><property name=\"bottom_attach\">2</property"
  "></packing></child><child><object class=\"GtkCheckButton\" id=\"length-"
  "adjust\"><property name=\"label\" translatable=\"yes\">A_utomatically i"
  "ncrease the length</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"receives_d"
  "efault\">False</property><property name=\"tooltip_text\" translatable=\""
  "yes\">Select this option to automatically increase the length of the pa"
  "nel if the plugins request more space.</property><property name=\"use_u"
  "nderline\">True</property><property name=\"draw_indicator\">True</prope"
  "rty></object><packing><property name=\"right_attach\">2</property><prop"
  "erty name=\"top_attach\">3</property><property name=\"bottom_attach\">4"
  "</property></packing></child></object></child></object></child><child t"
  "ype=\"label\"><object class=\"GtkLabel\" id=\"label5\"><property name=\""
  "visible\">True</property><property name=\"label\" translatable=\"yes\" "
  "comments=\"I18N: name of the section (frame) in the panel preferences w"
  "here the user can define the length and size of the panel\">Measurement"
  "s</property><attributes><attribute name=\"weight\" value=\"bold\"/></at"
  "tributes></object></child></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"position\">1</property></packing></chil"
  "d></object></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "label6\"><property name=\"visible\">True</property><property name=\"lab"
  "el\" translatable=\"yes\">D_isplay</property><property name=\"use_under"
  "line\">True</property></object><packing><property name=\"tab_fill\">Fal"
  "se</property></packing></child><child><object class=\"GtkVBox\" id=\"vb"
  "ox7\"><property name=\"visible\">True</property><property name=\"border"
  "_width\">6</property><property name=\"orientation\">vertical</property>"
  "<property name=\"spacing\">6</property><child><object class=\"GtkFrame\""
  " id=\"frame3\"><property name=\"visible\">True</property><property name"
  "=\"label_xalign\">0</property><property name=\"shadow_type\">none</prop"
  "erty><child><object class=\"GtkAlignment\" id=\"alignment3\"><property "
  "name=\"visible\">True</property><property name=\"left_padding\">12</pro"
  "perty><child><object class=\"GtkVBox\" id=\"vbox4\"><property name=\"vi"
  "sible\">True</property><property name=\"border_width\">6</property><pro"
  "perty name=\"orientation\">vertical</property><property name=\"spacing\""
  ">6</property><child><object class=\"GtkHBox\" id=\"hbox2\"><property na"
  "me=\"visible\">True</property><property name=\"spacing\">12</property><"
  "child><object class=\"GtkLabel\" id=\"label7\"><property name=\"visible"
  "\">True</property><property name=\"xalign\">0</property><property name="
  "\"label\" translatable=\"yes\">_Style:</property><property name=\"use_u"
  "nderline\">True</property><property name=\"mnemonic_widget\">background"
  "-style</property></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"position\">0</property></packing></child><child>"
  "<object class=\"GtkComboBox\" id=\"background-style\"><property name=\""
  "visible\">True</property><property name=\"model\">styles-store</propert"
  "y><child><object class=\"GtkCellRendererText\" id=\"cellrenderertext4\""
  "/><attributes><attribute name=\"text\">0</attribute></attributes></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"position\">1</property></packing></child></object><packing><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkHBox\" id=\"bg-alpha-box\"><property name=\"visible\">True</pr"
  "operty><property name=\"spacing\">12</property><property name=\"orienta"
  "tion\">vertical</property><child><object class=\"GtkHBox\" id=\"scale-b"
  "ox\"><property name=\"visible\">True</property><child><object class=\"G"
  "tkLabel\" id=\"label15\"><property name=\"visible\">True</property><pro"
  "perty name=\"xalign\">0</property><property name=\"label\" translatable"
  "=\"yes\">_Alpha:</property><property name=\"use_underline\">True</prope"
  "rty><property name=\"mnemonic_widget\">bg-alpha-scale</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkHScal"
  "e\" id=\"bg-alpha-scale\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"tooltip_text\""
  " translatable=\"yes\">Alpha value of the panel background, with 0 being"
  " fully transparent and 100 fully opaque.</property><property name=\"adj"
  "ustment\">background-alpha</property><property name=\"digits\">0</prope"
  "rty><property name=\"value_pos\">right</property></object><packing><pro"
  "perty name=\"position\">1</property></packing></child></object><packing"
  "><property name=\"position\">0</property></packing></child><child><obje"
  "ct class=\"GtkCheckButton\" id=\"auto-alpha\"><property name=\"label\" "
  "translatable=\"yes\">_Auto Alpha</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"receives_default\">False</property><property name=\"tooltip_text\" "
  "translatable=\"yes\">Check this box to automatically change the alpha o"
  "f the panel.</property><property name=\"use_underline\">True</property>"
  "<property name=\"draw_indicator\">True</property></object><packing><pro"
  "perty name=\"position\">1</property></packing></child></object><packing"
  "><property name=\"position\">1</property></packing></child><child><obje"
  "ct class=\"GtkHBox\" id=\"bg-color-box\"><property name=\"visible\">Tru"
  "e</property><property name=\"spacing\">12</property><child><object clas"
  "s=\"GtkLabel\" id=\"label16\"><property name=\"visible\">True</property"
  "><property name=\"xalign\">0</property><property name=\"label\" transla"
  "table=\"yes\">C_olor:</property><property name=\"use_underline\">True</"
  "property><property name=\"mnemonic_widget\">background-color</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"position\">0</property></packing></child><child><object class=\"G"
  "tkColorButton\" id=\"background-color\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"title\" translatable"
  "=\"yes\">Pick a Panel Color</property><property name=\"color\">#0000000"
  "00000</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"position\">1</property></packing></child></object"
  "><packing><property name=\"position\">2</property></packing></child><ch"
  "ild><object class=\"GtkHBox\" id=\"bg-image-box\"><property name=\"visi"
  "ble\">True</property><property name=\"spacing\">12</property><child><ob"
  "ject class=\"GtkLabel\" id=\"label19\"><property name=\"visible\">True<"
  "/property><property name=\"xalign\">0</property><property name=\"label\""
  " translatable=\"yes\">_File:</property><property name=\"use_underline\""
  ">True</property><property name=\"mnemonic_widget\">background-image</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkFileChooserButton\" id=\"background-image\"><property name=\"v"
  "isible\">True</property><property name=\"title\" translatable=\"yes\">S"
  "elect A Background Image</property></object><packing><property name=\"p"
  "osition\">1</property></packing></child></object><packing><property nam"
  "e=\"position\">3</property></packing></child></object></child></object>"
  "</child><child type=\"label\"><object class=\"GtkLabel\" id=\"label8\">"
  "<property name=\"visible\">True</property><property name=\"label\" tran"
  "slatable=\"yes\">Background</property><attributes><attribute name=\"wei"
  "ght\" value=\"bold\"/></attributes></object></child></object><packing><"
  "property name=\"expand\">False</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkFrame\" id=\"comp"
  "osited\"><property name=\"visible\">True</property><property name=\"lab"
  "el_xalign\">0</property><property name=\"shadow_type\">none</property><"
  "child><object class=\"GtkAlignment\" id=\"alignment4\"><property name=\""
  "visible\">True</property><property name=\"left_padding\">12</property><"
  "child><object class=\"GtkTable\" id=\"table2\"><property name=\"visible"
  "\">True</property><property name=\"border_width\">6</property><property"
  " name=\"n_rows\">2</property><property name=\"n_columns\">2</property><"
  "property name=\"column_spacing\">12</property><property name=\"row_spac"
  "ing\">6</property><child><object class=\"GtkLabel\" id=\"label9\"><prop"
  "erty name=\"visible\">True</property><property name=\"xalign\">0</prope"
  "rty><property name=\"label\" translatable=\"yes\" comments=\"I18N: labe"
  "l for the enter transparency slider\">_Enter:</property><property name="
  "\"use_underline\">True</property><property name=\"mnemonic_widget\">ent"
  "er-opacity-scale</property></object><packing><property name=\"x_options"
  "\">GTK_FILL</property></packing></child><child><object class=\"GtkLabel"
  "\" id=\"label10\"><property name=\"visible\">True</property><property n"
  "ame=\"xalign\">0</property><property name=\"label\" translatable=\"yes\""
  " comments=\"I18N: label for the leave transparency slider\">_Leave:</pr"
  "operty><property name=\"use_underline\">True</property><property name=\""
  "mnemonic_widget\">leave-opacity-scale</property></object><packing><prop"
  "erty name=\"top_attach\">1</property><property name=\"bottom_attach\">2"
  "</property><property name=\"x_options\">GTK_FILL</property></packing></"
  "child><child><object class=\"GtkHScale\" id=\"enter-opacity-scale\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"tooltip_text\" translatable=\"yes\">Transp"
  "arency when the pointer is hovering over the panel, with 0 being fully "
  "transparent and 100 fully opaque.</property><property name=\"adjustment"
  "\">enter-opacity</property><property name=\"digits\">0</property><prope"
  "rty name=\"value_pos\">right</property></object><packing><property name"
  "=\"left_attach\">1</property><property name=\"right_attach\">2</propert"
  "y></packing></child><child><object class=\"GtkHScale\" id=\"leave-opaci"
  "ty-scale\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"tooltip_text\" translatable="
  "\"yes\">Transparency when the pointer is not hovering over the panel, w"
  "ith 0 being fully transparent and 100 fully opaque.</property><property"
  " name=\"adjustment\">leave-opacity</property><property name=\"digits\">"
  "0</property><property name=\"value_pos\">right</property></object><pack"
  "ing><property name=\"left_attach\">1</property><property name=\"right_a"
  "ttach\">2</property><property name=\"top_attach\">1</property><property"
  " name=\"bottom_attach\">2</property></packing></child></object></child>"
  "</object></child><child type=\"label\"><object class=\"GtkLabel\" id=\""
  "label11\"><property name=\"visible\">True</property><property name=\"la"
  "bel\" translatable=\"yes\">Opacity</property><attributes><attribute nam"
  "e=\"weight\" value=\"bold\"/></attributes></object></child></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"positi"
  "on\">1</property></packing></child><child><object class=\"GtkAlignment\""
  " id=\"composited-info\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"xalign\">0</pr"
  "operty><property name=\"yalign\">1</property><property name=\"xscale\">"
  "0</property><property name=\"yscale\">0</property><child><object class="
  "\"GtkHBox\" id=\"hbox5\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"spacing\">6</"
  "property><child><object class=\"GtkImage\" id=\"image9\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"stock\">gtk-info</property><property name=\"icon-siz"
  "e\">5</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkLabel\" id=\"l"
  "abel17\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"xalign\">0</property><propert"
  "y name=\"label\" translatable=\"yes\">Enable compositing in the window "
  "manager for opacity settings in the panel.</property><property name=\"w"
  "rap\">True</property><property name=\"width_chars\">0</property></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child></object></child></object><packing><property name=\"expand\">Tru"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">2</property></packing></child></object><packing><property name="
  "\"position\">1</property></packing></child><child type=\"tab\"><object "
  "class=\"GtkLabel\" id=\"label12\"><property name=\"visible\">True</prop"
  "erty><property name=\"label\" translatable=\"yes\">Appeara_nce</propert"
  "y><property name=\"use_underline\">True</property></object><packing><pr"
  "operty name=\"position\">1</property><property name=\"tab_fill\">False<"
  "/property></packing></child><child><object class=\"GtkHBox\" id=\"hbox4"
  "\"><property name=\"visible\">True</property><property name=\"border_wi"
  "dth\">6</property><property name=\"spacing\">6</property><child><object"
  " class=\"GtkScrolledWindow\" id=\"scrolledwindow3\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"hscrollbar_policy\">automatic</property><property name=\"v"
  "scrollbar_policy\">automatic</property><property name=\"shadow_type\">e"
  "tched-in</property><child><object class=\"GtkTreeView\" id=\"item-treev"
  "iew\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"headers_visible\">False</property"
  "><property name=\"rules_hint\">True</property><property name=\"enable_s"
  "earch\">False</property></object></child></object><packing><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kVBox\" id=\"vbox6\"><property name=\"visible\">True</property><propert"
  "y name=\"orientation\">vertical</property><property name=\"spacing\">6<"
  "/property><child><object class=\"GtkButton\" id=\"item-up\"><property n"
  "ame=\"visible\">True</property><property name=\"sensitive\">False</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">True</property><property name=\"tooltip_text\" translatab"
  "le=\"yes\">Move currently selected item up by one row</property><child>"
  "<object class=\"GtkImage\" id=\"image3\"><property name=\"visible\">Tru"
  "e</property><property name=\"stock\">gtk-go-up</property></object></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkButton\" id=\"item-down\"><property name=\"visible\">True</propert"
  "y><property name=\"sensitive\">False</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">True</property>"
  "<property name=\"tooltip_text\" translatable=\"yes\">Move currently sel"
  "ected item down by one row</property><child><object class=\"GtkImage\" "
  "id=\"image4\"><property name=\"visible\">True</property><property name="
  "\"stock\">gtk-go-down</property></object></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"position\">1</pr"
  "operty></packing></child><child><object class=\"GtkButton\" id=\"item-a"
  "dd\"><property name=\"visible\">True</property><property name=\"sensiti"
  "ve\">False</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">True</property><property name=\"tooltip_t"
  "ext\" translatable=\"yes\">Add new item to this panel</property><child>"
  "<object class=\"GtkImage\" id=\"image5\"><property name=\"visible\">Tru"
  "e</property><property name=\"stock\">gtk-add</property></object></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"position\">2</property></packing></child><child><object class=\""
  "GtkButton\" id=\"item-remove\"><property name=\"visible\">True</propert"
  "y><property name=\"sensitive\">False</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">True</property>"
  "<property name=\"tooltip_text\" translatable=\"yes\">Remove currently s"
  "elected item</property><child><object class=\"GtkImage\" id=\"image6\">"
  "<property name=\"visible\">True</property><property name=\"stock\">gtk-"
  "remove</property></object></child></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"position\">3</property></packin"
  "g></child><child><object class=\"GtkButton\" id=\"item-properties\"><pr"
  "operty name=\"visible\">True</property><property name=\"sensitive\">Fal"
  "se</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">True</property><property name=\"tooltip_text\" tr"
  "anslatable=\"yes\">Edit the currently selected item</property><child><o"
  "bject class=\"GtkImage\" id=\"image7\"><property name=\"visible\">True<"
  "/property><property name=\"stock\">gtk-properties</property></object></"
  "child></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"position\">4</property></packing></child><child><object cla"
  "ss=\"GtkButton\" id=\"item-about\"><property name=\"visible\">True</pro"
  "perty><property name=\"sensitive\">False</property><property name=\"can"
  "_focus\">True</property><property name=\"receives_default\">True</prope"
  "rty><property name=\"tooltip_text\" translatable=\"yes\">Show about inf"
  "ormation of the currently selected item</property><child><object class="
  "\"GtkImage\" id=\"image8\"><property name=\"visible\">True</property><p"
  "roperty name=\"stock\">gtk-about</property></object></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"posit"
  "ion\">5</property></packing></child></object><packing><property name=\""
  "expand\">False</property><property name=\"position\">1</property></pack"
  "ing></child></object><packing><property name=\"position\">2</property><"
  "/packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"la"
  "bel14\"><property name=\"visible\">True</property><property name=\"labe"
  "l\" translatable=\"yes\">Ite_ms</property><property name=\"use_underlin"
  "e\">True</property></object><packing><property name=\"position\">2</pro"
  "perty><property name=\"tab_fill\">False</property></packing></child></o"
  "bject><packing><property name=\"position\">1</property></packing></chil"
  "d></object><packing><property name=\"position\">1</property></packing><"
  "/child><child internal-child=\"action_area\"><object class=\"GtkHButton"
  "Box\" id=\"dialog-action_area1\"><property name=\"visible\">True</prope"
  "rty><property name=\"layout_style\">end</property><child><object class="
  "\"GtkButton\" id=\"button-close\"><property name=\"label\">gtk-close</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">True</proper"
  "ty><property name=\"use_stock\">True</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">False</prop"
  "erty><property name=\"position\">0</property></packing></child><child><"
  "object class=\"GtkButton\" id=\"button-help\"><property name=\"label\">"
  "gtk-help</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">T"
  "rue</property><property name=\"use_stock\">True</property></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "False</property><property name=\"position\">1</property><property name="
  "\"secondary\">True</property></packing></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"pack_type\">end</p"
  "roperty><property name=\"position\">0</property></packing></child></obj"
  "ect></child><action-widgets><action-widget response=\"0\">button-close<"
  "/action-widget><action-widget response=\"1\">button-help</action-widget"
  "></action-widgets></object></interface>"
};

static const unsigned panel_preferences_dialog_ui_length = 33004u;

